version: '3.9'

services:
  jazz-band-parser:
    container_name: jazz-band-parser
    image: jazz-band-parser:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
    restart: unless-stopped
