version: '3.9'

services:
  jazz-band-parser:
    container_name: jazz-band-parser
    image: jazz-band-parser:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped
